version: '2'
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: always
    ports:
      - 8180:8080
    volumes:
      - ./:/var/jenkins_home
    links:
      - sonarqube
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000